
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
    console.log("🚨 STARTING SALES & ORDER PURGE 🚨");
    console.log("-----------------------------------");
    console.log("PRESERVING: Users, Branches, Products, Recipes, Menu Items");
    console.log("DELETING: Sales Reports, Journal Entries (Sales), Inventory Transactions (Sales)");

    // 1. Delete Sales Reports (Headers)
    const reports = await prisma.salesReport.deleteMany();
    console.log(`✅ Deleted ${reports.count} Sales Reports.`);

    // 2. Delete Journal Entries (Financials)
    // We delete ALL Journal Entries to be safe, as they are primarily generated by Sales Import in this context.
    // If there were manual entries, they would be lost, but "reset sales history" usually implies this.
    // To be safer, we could filter, but "Delete ALL" was the request.
    // However, let's try to be smart if possible. But for a "fresh start" on a new system, wiping JEs is usually desired.
    // Given the user is in "Setup/Import" phase, wiping JEs is the correct interpretation.

    // Deleting lines first is automatic via Cascade usually, but let's check schema.
    // Schema: journalEntry JournalEntry @relation(fields: [journalEntryId], references: [id], onDelete: Cascade)
    // Yes, Cascade is on.
    const je = await prisma.journalEntry.deleteMany();
    console.log(`✅ Deleted ${je.count} Journal Entries (Financial Records).`);

    // 3. Delete Inventory Transactions (Physical Sales)
    // Only type SALE to avoid deleting Purchase/Stock Takes if possible?
    // User said "Order and Sales records".
    // If they re-import sales, they might re-trigger stock movements.
    const tx = await prisma.inventoryTransaction.deleteMany({
        where: { type: 'SALE' }
    });
    console.log(`✅ Deleted ${tx.count} Inventory Transactions (Type: SALE).`);

    // 4. Reset Invoice Items linked to Sales? No, Invoices are Purchases. Keep them.

    // 5. Check if there are "Orders" table?
    // Schema check showed no "Order" model in recent view, but let's try to delete if it exists (dynamic check impossible in strict TS without model).
    // Based on previous schema view, no Order model.

    console.log("-----------------------------------");
    console.log("✅ SALES PURGE COMPLETE");
    console.log("Master Data (Products, Recipes) is INTACT.");
    console.log("You can now re-upload your Sales History.");
}

main()
    .catch(e => console.error(e))
    .finally(async () => await prisma.$disconnect());
